version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: test-backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
      - ./backend/.env:/var/www/html/.env
      - ./backend/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=test_db
      - DB_USER=admin
      - DB_PASS=password

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: ./web
    depends_on:
      - "backend"
    environment:
      WEBSOCKET_HOST: ${WEBSOCKET_HOST}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      WEBSOCKET_PROTOCOL: ${WEBSOCKET_PROTOCOL}
      WOPI_ENABLED: ${WOPI_ENABLED}
      LDAP_ENABLED: ${LDAP_IS_ENABLED}
      WOPI_CLIENT_URL: ${WOPI_CLIENT_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
    ports:
      - "80:80"
      - "443:443"
      - "8099:8099"
    volumes:
      - /etc/security:/etc/security
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
volumes:
  db_data:
